select 'INSERT INTO tpcapd01_vp_tecnologia (PCT_ID, PCA_CODCON, PCA_CODIGO, PCT_TP_TECNOLOGIA, PCT_FL_ATIVO, PCT_DT_CRIACAO, PCT_NM_USUARIOCRIACAO) ' ||
' VALUES(SQ_TPCAPD01_VP_TECNOLOGIA.NEXTVAL, '|| PCA_CODCON || ', '|| PCA_CODIGO || ', 1, 1, SYSDATE, ''RAFAEL.OLIVEIRA'');' || chr(13) ||
'INSERT INTO tpcapd01_vp_tecnologia (PCT_ID, PCA_CODCON, PCA_CODIGO, PCT_TP_TECNOLOGIA, PCT_FL_ATIVO, PCT_DT_CRIACAO, PCT_NM_USUARIOCRIACAO) ' ||
' VALUES(SQ_TPCAPD01_VP_TECNOLOGIA.NEXTVAL, '|| PCA_CODCON || ', '|| PCA_CODIGO || ', 2, 1, SYSDATE, ''RAFAEL.OLIVEIRA'');'
  from tpcapd01
 where pca_codcon != 90000 and pca_codcon != 90001;
