    SELECT DISTINCT DIA_SEMANA
      FROM (
        SELECT TO_CHAR(TO_DATE('10/09/2018', 'DD/MM/YYYY') - (ROWNUM - 1),'D') DIA_SEMANA
          FROM DUAL CONNECT BY ROWNUM <= TO_DATE('10/09/2018', 'DD/MM/YYYY') - TO_DATE('01/09/2018', 'DD/MM/YYYY') + 1
         ORDER by 2
    )
