-- Oracle visualizando os locks
SELECT os_user_name "OS User",
process "OS Pid",
oracle_username "Oracle User",
l.sid "SID",
DECODE(type,
'MR', 'Media Recovery',
'RT', 'Redo Thread',
'UN', 'User Name',
'TX', 'Transaction',
'TM', 'DML',
'UL', 'PL/SQL User Lock',
'DX', 'Distributed Xaction',
'CF', 'Control File',
'IS', 'Instance State',
'FS', 'File Set',
'IR', 'Instance Recovery',
'ST', 'Disk Space Transaction',
'TS', 'Temp Segment',
'IV', 'Library Cache Invalidation',
'LS', 'Log Start or Switch',
'RW', 'Row Wait',
'SQ', 'Sequence Number',
'TE', 'Extend Table',
'TT', 'Temp Table', type) "Lock Type",
DECODE(lmode,
0, 'None',
1, 'Null',
2, 'Row-S (SS)',
3, 'Row-X (SX)',
4, 'Share',
5, 'S/Row-X (SSX)',
6, 'Exclusive', lmode) "Lock Held",
DECODE(request,
0, 'None',
1, 'Null',
2, 'Row-S (SS)',
3, 'Row-X (SX)',
4, 'Share',
5, 'S/Row-X (SSX)',
6, 'Exclusive', request) "Lock Requested",
DECODE(block,
0, 'Not Blocking',
1, 'Blocking',
2, 'Global', block) "Status",
owner "Owner",
object_name "Object name"
FROM gv$locked_object lo, dba_objects do, gv$lock l
WHERE lo.object_id = do.object_id
AND l.sid = lo.session_id